export * from './addition.interface';
export * from './employee.interface';
export * from './client.interface';
export * from './error.interface';
export * from './token.interface';
export * from './user.interface';
export * from './room.interface';
export * from './service.interface';
export * from './booking.interface';
